### ISSUE TITLE
[BUG] $ref to external files not working?

### ISSUE THREAD

**Issue by BenHoopleEmpire** [asyncapi/jasyncapi-idea-plugin#101]
### Describe the bug.

this bug deals with the $ref variable not working as expected.

Context:
working with the $ref value is pretty critical for reducing repetition within our docs. I'll give the following basic example:

file: User.yaml
```
User:
  description: ...
  type: object
  properties:
    name:
      type: string
```
next file Admin.yaml:
```
Admin:
  desc: ...
  type: object
  properties:
    user:
      $ref: './User.yaml#User'
    privilege:
      type: string
```

Now if i reference Admin.yaml in a components section of an asyncapi.yaml file it fails
i.e. `$ref: '../CommonObjects/Admin.yaml#/Admin'`

I know the paths are correct because i've swapped them around and it loads, it is having a hard time with the references inside a file it references.

If this is expected behaviour I'd like to know that, but i feel like this should be possible. I've also looked for any settings but cant find anything that seems to line up with that.   

### Expected behavior

Expected to see the object being referenced while containing references itself. 

### Screenshots

![image](https://github.com/user-attachments/assets/1ca095be-db74-48b6-a8cc-b6ce71cc3d8b)

### How to Reproduce

This is all done in intellij, version 2024.1.4
1. create a .yaml file for a base object
2. create another .yaml file referencing that object
3. create a 3rd .yaml file which references the file from step 2.

### 🥦 Browser

Google Chrome

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!
