### ISSUE TITLE
[BUG] Intellij Plugin validation for exclusiveMaximum / exclusiveMinimum is wrong

### ISSUE THREAD

**Issue by fivetide** [asyncapi/jasyncapi-idea-plugin#157]
### Describe the bug.

when using exclusiveMaximum or exclusiveMinimum as defined in the JSON Schema Validation RFC, (https://datatracker.ietf.org/doc/html/draft-wright-json-schema-validation-00#section-5.5)  the plugin complains that the property should be a number, whereas it is supposed to be a boolean:
```
    exclusiveMaximum:
      messageId: exclusiveMaximum
      name: exclusiveMaximumExample
      title: Exclusive Maximum Validation Example
      summary: Demonstrates that a number must be strictly less than 50.
      payload:
        type: object
        properties:
          value:
            type: number
            maximum: 50
            exclusiveMaximum: true
        required:
          - value
        examples:
          - value: 49
            valid: true
          - value: 50
            valid: false

```

results in this error:

```
Error: This is not a valid AsyncAPI Schema Object.
127./components/messages/exclusiveMaximum/payload/properties/value/exclusiveMaximum should be number
127./components/messages/exclusiveMaximum/payload/properties/value/exclusiveMaximum should be number
```

### Expected behavior

the schema is considered valid

### Screenshots

![Image](https://github.com/user-attachments/assets/be195850-7d5e-4ad3-a6a4-7ed8cc972530)

### How to Reproduce

1. use the example provided.
2. see the preview tab

### 🥦 Browser

None

### 👀 Have you checked for similar open issues?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [x] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None
