### ISSUE TITLE
Plugin cannot deal with separate files

### ISSUE THREAD

**Issue by rost5000** [asyncapi/jasyncapi-idea-plugin#35]
#### Describe the bug
I have the following structure of the assyncapi:
1. `assyncapi.yml`:
    ```yaml
    asyncapi: '2.6.0'
    info:
      title: Account Service
      version: 1.0.0
      description: This service is in charge of processing user signups
    channels:
      user/signedup:
        subscribe:
          message:
            $ref: './messages/common.yaml#/components/messages/UserSignedUp'
    ```
2. `./messages/common.yaml`
   ```yaml
    asyncapi: '2.6.0'
    info:
      title: Account Service
      version: 1.0.0
      description: This service is in charge of processing user signups
    channels:
      {}
    components:
      messages:
        UserSignedUp:
          payload:
            type: object
            properties:
              displayName:
                type: string
                description: Name of the user
              email:
                type: string
                format: email
                description: Email of the user
   ```
 When I press a `preview` button <img src="https://github.com/asyncapi/jasyncapi-idea-plugin/assets/24576320/75e2c883-7120-4e74-9bed-446ac13f98ff"  width="80" height="20">. I see the error:
![image](https://github.com/asyncapi/jasyncapi-idea-plugin/assets/24576320/f14d307a-fc0f-49fc-affd-a402dd1a8dee)

#### How to Reproduce
1. Open IntelijIdea (I have 2023.2)
2. Clone the project: https://github.com/rost5000/assyncapi-dummy-view.git
3. Open the file: src/main/resources/assyncapi.yml
4. Press the button `preview`

#### Expected behavior
I expect the view in idea like: [this](https://studio.asyncapi.com/?url=https://raw.githubusercontent.com/asyncapi/asyncapi/master/examples/simple.yml)

**Comment by theschles** [comment]
Hi!  OUt of curiosity, does it work with absolute paths?

**Comment by Pakisan** [comment]
@rost5000 Hi!

It's because of 2.6.0. I submitted update to JetBrains. Will be available on Monday(few days for review from their side)

**Comment by Pakisan** [comment]
@rost5000 hi!

I checked both variants on current and new versions- 2.2.0, 2.3.0. Reference resolving works great, with specs that you were provided

Scenario 1:

spec(assyncapi.yml):
```yaml
asyncapi: 2.5.0
info:
  title: Account Service
  version: 1.0.0
  description: This service is in charge of processing user signups
channels:
  user/signedup:
    subscribe:
      message:
        $ref: "./messages/userSignedUp.yaml"
```

ref:
```yaml
payload:
  type: object
  properties:
    displayName:
      type: string
      description: Name of the user(2_2)
    email:
      type: string
      format: email
      description: Email of the user(3_3)
```

<img width="1597" alt="Screenshot 2023-09-04 at 10 04 57" src="https://github.com/asyncapi/jasyncapi-idea-plugin/assets/3388414/9f468582-64a6-4c6c-9474-d3aa29401fa9">


Scenario 2:
spec(assyncapi.yml):
```yaml
asyncapi: 2.6.0
info:
  title: Account Service 22
  version: 1.0.0
  description: This service is in charge of processing user signups
channels:
  user/signedup:
    subscribe:
      message:
        $ref: './messages/common.yaml#/components/messages/UserSignedUp'
```

ref:
```yaml
asyncapi: 2.6.0
info:
  title: Account Service--
  version: 1.0.0
  description: This service is in charge of processing user signups
channels:
  {}
components:
  messages:
    UserSignedUp:
      payload:
        type: object
        properties:
          displayName:
            type: string
            description: Name of the user
          email:
            type: string
            format: email
            description: Email of the user
```

<img width="1597" alt="Screenshot 2023-09-04 at 10 03 11" src="https://github.com/asyncapi/jasyncapi-idea-plugin/assets/3388414/1d117704-5d05-4ca5-92d4-f02721f291ad">


Looks like problem is only in preview view which was provided by IDEA, not my plugin. Will try to research what went wrong and create an issue

For now, you can still use the preview in the browser button. It allows to render specifications inside IDEA or in any installed browser with refresh on save

<img width="232" alt="Screenshot 2023-09-04 at 10 07 16" src="https://github.com/asyncapi/jasyncapi-idea-plugin/assets/3388414/db47fa96-9dee-477b-9cac-9c3518a78161">
